# Generated by Django 4.1.7 on 2023-05-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_rename_genres_movie_genre_comment_movie_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='genre',
            new_name='genres',
        ),
    ]
