# Generated by Django 4.1.7 on 2023-06-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0006_alter_comment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
