# Generated by Django 4.1.7 on 2023-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0007_director_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
